<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dobot_operator_gui</name>
  <version>0.6.0</version>
  <description>Safe unified CR5, SC3000, gripper, and SEER AGV operator panel.</description>
  <maintainer email="zsx@example.com">zsx</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>dobot_msgs_v3</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-pyftpdlib</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>seer_agv_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
